#pragma kernel CSMain

RWTexture2D<float> Result;
float4 _Center;

[numthreads(3,3,1)]
void CSMain (uint3 id : SV_GroupThreadID)
{
    uint2 uv = _Center.xy * 1024 + id.xy - uint2(1, 1);
    float value = Result[uv];
    Result[uv] += (id.x == id.y == 1)? value * -0.5 : value * 0.1;
    //if (id.x == id.y == 1) {
    //    Result[uv] += value * -0.5;
    //}
    //else
    //    Result[uv] += value * 0.1;
    //
}
